In [2]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [4]:
#Carga desde un archivo .csv sin índice
data = pd.read_csv('Porto_Portugal.csv')
data.head(5)

,Unnamed: 0,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
0,0,46609,Byron Beach Cabin,208641,Glen,2010-08-21,within an hour,100%,83%,f,...,4.92,4.96,5.00,5.00,4.92,4.77,f,1,1,0
1,1,59459,Tea on the Terrace,285576,Liz,2010-11-12,within an hour,100%,93%,t,...,4.93,4.94,4.94,4.94,4.80,4.92,f,1,0,1
2,2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100%,96%,t,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
3,3,113407,Byron Bay Hinterland House & Pool POCKET PINES,576938,Jo,2011-05-10,within an hour,100%,95%,t,...,4.88,4.75,4.96,4.98,4.88,4.71,f,1,1,0
4,4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100%,100%,f,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0

In [6]:
#Eliminar columnas inncesarias
#axis = 1 para columnas
#axis = 0 para filas
data1 = data.drop(['Unnamed: 0'],axis=1)
data1

,id,name,host_id,host_name,host_since,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_listings_count,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count,calculated_host_listings_count_entire_homes,calculated_host_listings_count_private_rooms
0,46609,Byron Beach Cabin,208641,Glen,2010-08-21,within an hour,100%,83%,f,1,...,4.92,4.96,5.00,5.00,4.92,4.77,f,1,1,0
1,59459,Tea on the Terrace,285576,Liz,2010-11-12,within an hour,100%,93%,t,1,...,4.93,4.94,4.94,4.94,4.80,4.92,f,1,0,1
2,111036,5 Star Luxury @ Tweed Coast - Salt Village,569563,Tricia,2011-05-09,within an hour,100%,96%,t,1,...,4.97,4.94,4.84,4.92,4.97,4.88,t,1,1,0
3,113407,Byron Bay Hinterland House & Pool POCKET PINES,576938,Jo,2011-05-10,within an hour,100%,95%,t,1,...,4.88,4.75,4.96,4.98,4.88,4.71,f,1,1,0
4,259951,Rosebank Farmhouse,1340489,Ann-Marie,2011-10-27,within an hour,100%,100%,f,1,...,4.88,4.76,5.00,5.00,4.94,4.71,f,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6241,1309169243696998503,Tweed Coastal Retreat,8586213,Matthew,2013-09-02,NaN,NaN,NaN,f,1,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6242,1309580556361446644,13 William - Oceanstays - Pet Friendly,498657660,Oceanstays,2023-01-30,within an hour,100%,99%,t,39,...,NaN,NaN,NaN,NaN,NaN,NaN,t,39,39,0
6243,1310599322159916197,La Casita Studio,472492532,Camila,2022-07-31,NaN,NaN,NaN,f,2,...,NaN,NaN,NaN,NaN,NaN,NaN,t,1,1,0
6244,1310616537700203937,Rachana.,152421180,Your Luxury Escape,2017-09-28,within a few hours,84%,99%,t,66,...,NaN,NaN,NaN,NaN,NaN,NaN,t,66,61,5
6245,1310716580562175377,Bayshore Bungalow No.14,664353848,Naomi,2024-11-28,within an hour,100%,100%,f,12,...,NaN,NaN,NaN,NaN,NaN,NaN,t,12,12,0

In [8]:
#Identificar valores nulos por columna
valores_nulos=data1.isnull().sum()
valores_nulos

id                                                 0
name                                               0
host_id                                            0
host_name                                          0
host_since                                         0
host_response_time                               723
host_response_rate                               723
host_acceptance_rate                             518
host_is_superhost                                104
host_listings_count                                0
host_identity_verified                             0
neighbourhood_cleansed                             0
neighbourhood_group_cleansed                    6246
latitude                                           0
longitude                                          0
property_type                                      0
room_type                                          0
accommodates                                       0
bathrooms                                        378
bathrooms_text                                     0
bedrooms                                          34
beds                                             386
price                                            378
minimum_nights                                     0
maximum_nights                                     0
minimum_minimum_nights                             0
maximum_minimum_nights                             0
minimum_maximum_nights                             0
maximum_maximum_nights                             0
minimum_nights_avg_ntm                             0
maximum_nights_avg_ntm                             0
has_availability                                  35
availability_30                                    0
availability_60                                    0
availability_90                                    0
availability_365                                   0
number_of_reviews                                  0
number_of_reviews_ltm                              0
number_of_reviews_l30d                             0
review_scores_rating                            1085
review_scores_accuracy                          1087
review_scores_cleanliness                       1087
review_scores_checkin                           1087
review_scores_communication                     1087
review_scores_location                          1087
review_scores_value                             1087
instant_bookable                                   0
calculated_host_listings_count                     0
calculated_host_listings_count_entire_homes        0
calculated_host_listings_count_private_rooms       0
dtype: int64

In [10]:
data3=data.copy()

Generar una función para cada una de las siguientes acciones:

 a) Reemplazar valores nulos con el método de “mediana” en las columnas tipo “numeric (int y float)”
 
 b) Reemplazar valores nulos con el método de “ffill” en las columnas tipo “object, datetime y category”
 
 c) Reemplazar valores nulos con el método de “bfill” en las columnas tipo “object, datetime y category”
 
 d) Reemplazar valores nulos con el método de “string concreto” en las columnas tipo “object, datetime y category”
 
 e) Reemplazar valores nulos con el método de “constante” en las columnas tipo “numeric (int y float)”

In [53]:
def sust_prom(dataframe):
    #Separo columnas cuantitativas del dataframe
    cuantitativas_con_nulos = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    #Separo columnas cualitativas del dataframe
    cualitativas = dataframe.select_dtypes(include=['object', 'datetime','category'])
    #Sustituir valores nulos con promedio o media
    cuantitativas = cuantitativas_con_nulos.fillna(round(cuantitativas_con_nulos.mean(), 1))
    # Unimos el dataframe cuantitativo limpio con el dataframe cualitativo
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

def sust_ffill(dataframe):
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    cualitativas = cualitativas_con_nulos.fillna(method='ffill')
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

def sust_bfill(dataframe):
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    cualitativas = cualitativas_con_nulos.fillna(method='bfill')
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)


def sust_string(dataframe,cadena):
    cuantitativas = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    cualitativas_con_nulos = dataframe.select_dtypes(include=['object', 'datetime','category'])
    cualitativas = cualitativas_con_nulos.fillna(cadena)
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

def sust_constante(dataframe,constante):
    cuantitativas_con_nulos = dataframe.select_dtypes(include=['float64', 'int64','float','int'])
    cualitativas = dataframe.select_dtypes(include=['object', 'datetime','category'])
    cuantitativas = cuantitativas_con_nulos.fillna(constante)
    Datos_sin_nulos = pd.concat([cuantitativas, cualitativas], axis=1)
    
    return(Datos_sin_nulos)

In [ ]:
sust_mean = sust_prom(data3)
sust_mean.to_csv('sustitución_promedio.csv')
sust_mean.isnull().sum()

In [ ]:
sust_forward = sust_ffill(data3)
sust_forward.to_csv('sustitución_ffill.csv')
sust_forward.isnull().sum()

In [ ]:
sust_backward = sust_bfill(data3)
sust_backward.to_csv('sustitución_bfill.csv')
sust_backward.isnull().sum()

In [ ]:
sust_cadena = sust_string(data3,'within a day')
sust_cadena.to_csv('sustitución_string.csv')
sust_cadena.isnull().sum()

In [55]:
sust_cons = sust_constante(data3,5)
sust_cons.to_csv('sustitución_constante.csv')
sust_cons.isnull().sum()

Unnamed: 0                                        0
id                                                0
host_id                                           0
host_listings_count                               0
neighbourhood_group_cleansed                      0
latitude                                          0
longitude                                         0
accommodates                                      0
bathrooms                                         0
bedrooms                                          0
beds                                              0
minimum_nights                                    0
maximum_nights                                    0
minimum_minimum_nights                            0
maximum_minimum_nights                            0
minimum_maximum_nights                            0
maximum_maximum_nights                            0
minimum_nights_avg_ntm                            0
maximum_nights_avg_ntm                            0
availability_30                                   0
availability_60                                   0
availability_90                                   0
availability_365                                  0
number_of_reviews                                 0
number_of_reviews_ltm                             0
number_of_reviews_l30d                            0
review_scores_rating                              0
review_scores_accuracy                            0
review_scores_cleanliness                         0
review_scores_checkin                             0
review_scores_communication                       0
review_scores_location                            0
review_scores_value                               0
calculated_host_listings_count                    0
calculated_host_listings_count_entire_homes       0
calculated_host_listings_count_private_rooms      0
name                                              0
host_name                                         0
host_since                                        0
host_response_time                              723
host_response_rate                              723
host_acceptance_rate                            518
host_is_superhost                               104
host_identity_verified                            0
neighbourhood_cleansed                            0
property_type                                     0
room_type                                         0
bathrooms_text                                    0
price                                           378
has_availability                                 35
instant_bookable                                  0
dtype: int64